version: '3'

tasks:
  tag:
    desc: Bumps the minor version and pushes the tag
    cmds:
      - |
        # Check if git is dirty
        if [[ -n $(git status -s) ]]; then
          echo "Error: Git working directory is dirty. Please commit or stash changes first."
          exit 1
        fi
        
        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        
        # Extract version numbers
        MAJOR=$(echo $LATEST_TAG | cut -d. -f1 | tr -d 'v')
        MINOR=$(echo $LATEST_TAG | cut -d. -f2)
        PATCH=$(echo $LATEST_TAG | cut -d. -f3)
        
        # Bump minor version
        NEW_MINOR=$((MINOR + 1))
        NEW_TAG="v$MAJOR.$NEW_MINOR.0"
        
        # Create and push the new tag
        git tag $NEW_TAG
        git push origin $NEW_TAG
        
        echo "Created and pushed new tag: $NEW_TAG" 